# Generated by Django 4.0.5 on 2022-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ballot_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
