# Generated by Django 4.0.5 on 2022-06-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_candidate_ballot_number_candidate_vote_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='portfolio',
            new_name='position',
        ),
    ]
