# Generated by Django 4.0.5 on 2022-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_position_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
