# Generated by Django 4.0.5 on 2022-06-25 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_election_date_of_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date_of_election',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
