# Generated by Django 4.0.5 on 2022-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_candidate_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
    ]
