# Generated by Django 4.0.5 on 2023-07-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_no_votes_candidate_no_votes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='precedence',
            field=models.IntegerField(default=1),
        ),
    ]
