# Generated by Django 4.0.5 on 2022-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voted_for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_co',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_gp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_lp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_sp',
            field=models.BooleanField(default=False),
        ),
    ]
