# Generated by Django 4.0.5 on 2022-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='form',
        ),
        migrations.AddField(
            model_name='user',
            name='external_key',
            field=models.CharField(default='', max_length=8),
        ),
    ]
