# Generated by Django 4.0.5 on 2022-06-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_form_user_external_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_done_voting',
        ),
    ]
