# Generated by Django 4.0.5 on 2022-06-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_done_voting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='voted_for_co',
            new_name='voted_for_cob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='voted_for_lp',
            new_name='voted_for_cog',
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_csb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_csg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_dhpb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_dhpg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_ecpb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_ecpg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_hpb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_hpg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_hspb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_hspg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_lpb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_lpg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_ppb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_ppg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_sgpb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voted_for_sgpg',
            field=models.BooleanField(default=False),
        ),
    ]
