# Generated by Django 4.0.5 on 2025-07-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_voted_for_ppb_user_voted_for_day_std_coordinator_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voted_for_all',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_cob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_cog',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_csb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_csg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_day_std_coordinator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_day_std_coordinator_g',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_dhpb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_dhpg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_ecpb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_ecpg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_gp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_hpb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_hpg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_hspb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_hspg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_lpb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_lpg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_sgpb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_sgpg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_sp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_uafb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voted_for_uafg',
        ),
    ]
