# Generated by Django 4.0.5 on 2025-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_voted_for_all_remove_user_voted_for_cob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_votes_cast',
            field=models.IntegerField(default=0),
        ),
    ]
