# Generated by Django 4.0.5 on 2025-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_total_votes_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='already_voted',
            field=models.BooleanField(default=False),
        ),
    ]
