from enum import Enum


class PositionName(Enum):
    # SENIOR PREFECTS
    SP = "SENIOR BOYS' PREFECT"   # SENIOR PREFECT
    GP = "SENIOR GIRLS' PREFECT"   # GIRLS PREFECT
    # COMPOUNT
    COB = 'COMPOUND, UTILITY & FURNITURE OVERSEER (BOYS) '
    COG = 'COMPOUND, UTILITY & FURNITURE OVERSEER (GIRLS)'
    # SPORTS
    SGPB = 'SPORTS & GAMES PREFECT (BOYS)'  # SPORTS
    SGPG = 'SPORTS & GAMES PREFECT (GIRLS)'
    # DINING HALL
    DHPB = 'DINING HALL PREFECT (BOYS)'
    DHPG = 'DINING HALL PREFECT (GIRLS)'
    # ENTERTAINMENT
    ECPB = 'ENTERTAINMENT & CULTURE PREFECT (BOYS)'
    ECPG = 'ENTERTAINMENT & CULTURE PREFECT (GIRLS)'
    # LIBRARY
    LPB = 'LIBRARY PREFECT (BOYS)'   # LIBRARY PREFECT
    LPG = 'LIBRARY PREFECT (GIRLS)'   # LIBRARY PREFECT
    # CHAPEL STEWARD
    CSB = 'CHAPEL STEWARD (BOYS)'
    CSG = 'CHAPEL STEWARD (GIRLS)'
    # PRE
    PPB = 'PREPS PREFECT (BOYS)'
    PPG = 'PREPS PREFECT (GIRLS)'
    # HEALTH
    HSPB = 'HEALTH & SANITATION PREFECT (BOYS)'
    HSPG = 'HEALTH & SANITATION PREFECT (GIRLS)'
    # HOUSE 
    HPB = 'HOUSE PREFECT (BOYS)'
    HPG = 'HOUSE PREFECT (GIRLS)'