from enum import Enum


class PortfolioName(Enum):
    SP = 'SRC PRESIDENT'   # SENIOR PREFECT
    GP = 'GIRLS PREFECT'   # GIRLS PREFECT
    CO = 'COMPOUND OVERSEER'   # COMPOUND OVERSEER
    LP = 'LIBRARY PREFECT'   # LIBRARY PREFECT
    EP = 'ENTERTAINMENT PREFECT'
    PO = 'PROTOCOL OFFICER'
