from enum import Enum


class PositionName(Enum):
    # SENIOR PREFECTS
    SP = "SENIOR BOYS PREFECT"   # SENIOR PREFECT
    GP = "SENIOR GIRLS PREFECT"   # GIRLS PREFECT
    # COMPOUND
    COB = 'COMPOUND OVERSEER (BOYS)'
    COG = 'COMPOUND OVERSEER (GIRLS)'
    # UTILITY AND FURNITURE
    UAFB = 'UTILITY and FURNITURE (BOYS)'
    UAFG = 'UTILITY and FURNITURE (GIRLS)'
    # SPORTS
    SGPB = 'SPORTS & GAMES PREFECT (BOYS)'  # SPORTS
    SGPG = 'SPORTS & GAMES PREFECT (GIRLS)'
    # DINING HALL
    DHPB = 'DINING HALL PREFECT (BOYS)'
    DHPG = 'DINING HALL PREFECT (GIRLS)'
    # ENTERTAINMENT
    ECPB = 'ENTERTAINMENT & CULTURE PREFECT (BOYS)'
    ECPG = 'ENTERTAINMENT & CULTURE PREFECT (GIRLS)'
    # CHAPEL STEWARD
    CSB = 'CHAPEL STEWARD (BOYS)'
    CSG = 'CHAPEL STEWARD (GIRLS)'
    # PREPS AND LIBRARY
    PLPB = 'PREPS and LIBRARY PREFECT (BOYS)'
    PLPG = 'PREPS and LIBRARY PREFECT (GIRLS)'
    # HEALTH
    HSPB = 'HEALTH - HYGIENE and ATTIRE PREFECT (BOYS)'
    HSPG = 'HEALTH - HYGIENE and ATTIRE PREFECT (GIRLS)'
    # HSPB = 'HEALTH - SANITATION and ATTIRE PREFECT (BOYS)'
    # HSPG = 'HEALTH - SANITATION and ATTIRE PREFECT (GIRLS)'
    # HOUSE
    HPB = 'HOUSE PREFECT (BOYS)'
    HPG = 'HOUSE PREFECT (GIRLS)'
    # DAY STUDENTS COORDINATOR
    DSCB = 'DAY STUDENTS COORDINATOR (BOYS)'
    DSCG = 'DAY STUDENTS COORDINATOR (GIRLS)'


class Sex(Enum):
    M = 'M'
    F = 'F'


class House(Enum):
    ASANTE = 'ASANTE'
    BOTWE = 'BOTWE'
    KALEDZI = 'KALEDZI'
    KUMI = 'KUMI'
